### ISSUE TITLE
webchuck ACE syntax highlight

### ISSUE THREAD

**Issue by Kizjkre** [ccrma/webchuck#28]
- [ ] All 1.5.x.x new syntax
- [ ] Hex numbers

**Comment by terryzfeng** [comment]
Following up on this, would we want this in the Monaco IDE editor, Ace Editor, or some variant of Prism.js? @Kizjkre

**Comment by terryzfeng** [comment]
Oh yeah, I added `eon` and a couple other things manually to the syntax highlight list of Monaco here: https://github.com/terryzfeng/webchuck-ide/blob/871695ac1505779a9f87aae8f49e0f03e38d3e17/src/components/monaco/chuck-lang.ts#L66

Hex is handled here:
https://github.com/terryzfeng/webchuck-ide/blob/871695ac1505779a9f87aae8f49e0f03e38d3e17/src/components/monaco/chuck-lang.ts#L193-L196

I guess it's all good on the IDE then :)
