### ISSUE TITLE
chugin support

### ISSUE THREAD

**Issue by nshaheed** [ccrma/webchuck#3]
:)

**Comment by terryzfeng** [comment]
:)

**Comment by terryzfeng** [comment]
Hi @lmaxwell, we're actively experimenting with support for webchugins! Hold on tight!

**Comment by terryzfeng** [comment]
#31 Development is in the works! Stay tuned!

**Comment by terryzfeng** [comment]
@lmaxwell Chugins are supported in WebChucK as of v1.2.7. Chugins can be built for web from the official [chugins repository](https://github.com/ccrma/chugins) using `make web`. These chugins can be uploaded into WebChucK for usage on the web. 

```ts
Chuck.loadChugin("path/to/chugin.chug.wasm");
theChucK = await Chuck.init([]);
```

We have future plans to host prebuilt chugins online, and get them integrated into WebChucK IDE.
